package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	_ resource.ResourceWithConfigure   = &wireguardPeerResource{}
	_ resource.ResourceWithImportState = &wireguardPeerResource{}
)

type wireguardPeerResource struct{ client *Client }

type wireguardPeerModel struct {
	ID           types.String `tfsdk:"id"`
	GroupID      types.String `tfsdk:"group_id"`
	Name         types.String `tfsdk:"name"`
	PublicKey    types.String `tfsdk:"public_key"`
	EndpointHost types.String `tfsdk:"endpoint_host"`
	IP           types.String `tfsdk:"ip"`
	Config       types.String `tfsdk:"config"`
}

type apiWireGuardPeer struct {
	Name      string  `json:"name"`
	PublicKey string  `json:"public_key"`
	IP        *string `json:"ip"`
}

type apiWireGuardPeerCreated struct {
	Peer    apiWireGuardPeer `json:"peer"`
	Config  string           `json:"config"`
	Warning *string          `json:"warning"`
}

type apiWireGuardStatus struct {
	Configured bool               `json:"configured"`
	Peers      []apiWireGuardPeer `json:"peers"`
}

func NewWireGuardPeerResource() resource.Resource { return &wireguardPeerResource{} }

func (r *wireguardPeerResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_wireguard_peer"
}

func (r *wireguardPeerResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	replace := []planmodifier.String{stringplanmodifier.RequiresReplace()}
	keep := []planmodifier.String{stringplanmodifier.UseStateForUnknown()}
	resp.Schema = schema.Schema{
		Description: "A device (e.g. a laptop) allowed in a lab group through the router's WireGuard (vmmanager_group with " +
			"wireguard = true). Without public_key the server generates the key pair: `config` then holds the private key " +
			"(sensitive, kept in the state only). Every change recreates the device.",
		Attributes: map[string]schema.Attribute{
			"id":       schema.StringAttribute{Computed: true, PlanModifiers: keep, Description: "<group_id>/<name>"},
			"group_id": schema.StringAttribute{Required: true, PlanModifiers: replace},
			"name":     schema.StringAttribute{Required: true, PlanModifiers: replace, Description: "Device name (lowercase letters, digits, '-')."},
			"public_key": schema.StringAttribute{Optional: true, Computed: true, PlanModifiers: append(replace, keep...),
				Description: "The device's WireGuard public key (wg pubkey). Unset: generated by the server."},
			"endpoint_host": schema.StringAttribute{Optional: true, PlanModifiers: replace,
				Description: "Host name / address of the vmmanager host in the client config (default: the server's WG_ENDPOINT_HOST or LAN address)."},
			"ip": schema.StringAttribute{Computed: true, PlanModifiers: keep, Description: "Tunnel address of the device."},
			"config": schema.StringAttribute{Computed: true, Sensitive: true, PlanModifiers: keep,
				Description: "wg-quick client config (`nmcli connection import type wireguard file …` / WireGuard apps). Holds the " +
					"private key when the server generated it; null after an import."},
		},
	}
}

func (r *wireguardPeerResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = configureClient(req, resp)
}

func (r *wireguardPeerResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan wireguardPeerModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := map[string]any{"name": plan.Name.ValueString(), "public_key": strPtr(plan.PublicKey), "endpoint_host": strPtr(plan.EndpointHost)}
	var out apiWireGuardPeerCreated
	if err := r.client.Do(ctx, "POST", "/groups/"+plan.GroupID.ValueString()+"/wireguard/peers", body, &out); err != nil {
		resp.Diagnostics.AddError("Cannot add WireGuard device", err.Error())
		return
	}
	if out.Warning != nil && *out.Warning != "" {
		resp.Diagnostics.AddWarning("Device not applied on the router yet", *out.Warning)
	}
	plan.ID = types.StringValue(plan.GroupID.ValueString() + "/" + out.Peer.Name)
	plan.PublicKey = types.StringValue(out.Peer.PublicKey)
	plan.IP = strOrNull(out.Peer.IP)
	plan.Config = types.StringValue(out.Config)
	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// refresh returns false if the group or the device no longer exists.
func (r *wireguardPeerResource) refresh(ctx context.Context, m *wireguardPeerModel, d diags) bool {
	var st apiWireGuardStatus
	if err := r.client.Do(ctx, "GET", "/groups/"+m.GroupID.ValueString()+"/wireguard", nil, &st); err != nil {
		if IsNotFound(err) {
			return false
		}
		d.AddError("Cannot read the group's WireGuard", err.Error())
		return true
	}
	for _, p := range st.Peers {
		if p.Name == m.Name.ValueString() {
			m.PublicKey = types.StringValue(p.PublicKey)
			m.IP = strOrNull(p.IP)
			return true
		}
	}
	return false
}

func (r *wireguardPeerResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state wireguardPeerModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, &state, &resp.Diagnostics) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

// Update is never called with a change (every attribute recreates the device)
func (r *wireguardPeerResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan wireguardPeerModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

func (r *wireguardPeerResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state wireguardPeerModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	err := r.client.Do(ctx, "DELETE", "/groups/"+state.GroupID.ValueString()+"/wireguard/peers/"+url.PathEscape(state.Name.ValueString()), nil, nil)
	if err != nil && !IsNotFound(err) {
		resp.Diagnostics.AddError("Cannot remove WireGuard device", err.Error())
	}
}

// ImportState takes "<group_id>/<name>" (config stays null: the private key isn't stored server-side).
func (r *wireguardPeerResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	groupID, name, ok := strings.Cut(req.ID, "/")
	if !ok || groupID == "" || name == "" {
		resp.Diagnostics.AddError("Invalid import id", "expected <group_id>/<name>, e.g. 3/laptop")
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("group_id"), groupID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
}
