"""Disconnected kubeadm clusters (docs/disconnected.md "Kubernetes (kubeadm)")

The group router is the bastion, as for disconnected OpenShift: it runs the mirror registry and keeps its
internet access; the cluster's nodes only pull from the registry.

    images      `kubeadm config images list` of the exact Kubernetes patch (kubeadm downloaded on the router,
                which also resolves a minor to its latest patch: dl.k8s.io/release/stable-<minor>.txt), Flannel's
                images (from its manifest, also fetched by the router and handed to the first control plane),
                the demo image and the user's extra images; skopeo copies them on the router (copylist).
    layout      one registry namespace per upstream registry, the upstream path below it:
                registry.k8s.io/coredns/coredns:v1.12.1 -> registry.<domain>:8443/k8s/coredns/coredns:v1.12.1
                (Quay needs a namespace: registry.k8s.io/pause can't be pushed as "pause")
    nodes       containerd hosts.toml per upstream registry (/etc/containerd/certs.d/<registry>/hosts.toml):
                mirror https://registry.<domain>:8443/v2/<namespace> with override_path, the registry CA; the
                upstream stays the `server` (unreachable: what a pod pulling an un-mirrored image hits). Pods
                keep their usual image names (nginx:alpine, registry.k8s.io/...): nothing to rewrite.
    packages    containerd.io / kube* come from the internet at first boot, through a temporary egress
                exemption of the node's address (router.egress.exempt, owner cluster:<name>) removed as soon as
                its packages are in, before kubeadm pulls any image: it stands for the customer's golden image /
                internal package repo. Nodes added day 2 do the same.
"""
import base64
import logging
import re
from typing import Any, Dict, List, Optional, Tuple

from app.services.cluster_drivers import FLANNEL_MANIFEST

logger = logging.getLogger(__name__)

# Upstream registry -> namespace in the mirror registry. Others: the host name with '-' for '.' / ':'
NAMESPACES = {"registry.k8s.io": "k8s", "docker.io": "docker", "ghcr.io": "ghcr", "quay.io": "quay"}
# containerd hosts.toml `server` (the upstream) when it isn't https://<registry>
SERVERS = {"docker.io": "https://registry-1.docker.io"}
# Mirrored with every disconnected cluster, for a first test (kubectl create deployment web --image=nginx:alpine)
DEMO_IMAGE = "docker.io/library/nginx:alpine"
# Registry sizes when a kubeadm cluster enables it (skopeo only, no oc-mirror: much less than OpenShift)
REGISTRY_SIZES = {"memory_mb": 4096, "vcpus": 2, "disk_gb": 60}
CA_PATH = "/etc/containerd/certs.d/vmm-registry-ca.crt"
RESOLVE_TIMEOUT = 15 * 60


def parse(ref: str) -> Dict[str, Optional[str]]:
    """Docker-style reference -> {registry, path, tag, digest} (docker.io/library/... for short names)"""
    ref = ref.strip()
    if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._:/@+-]*$", ref):
        raise ValueError(f"'{ref}' is not an image reference")
    name, _, digest = ref.partition("@")
    first, _, rest = name.partition("/")
    if rest and ("." in first or ":" in first or first == "localhost"):
        registry, path = first.lower(), rest
    else:
        registry, path = "docker.io", name
    if registry in ("index.docker.io", "registry-1.docker.io"):
        registry = "docker.io"
    tag = None
    last = path.rsplit("/", 1)[-1]
    if ":" in last:
        path, tag = path.rsplit(":", 1)
    if registry == "docker.io" and "/" not in path:
        path = "library/" + path
    if not tag and not digest:
        tag = "latest"
    if path != path.lower():
        raise ValueError(f"'{ref}': repository names are lowercase")
    return {"registry": registry, "path": path, "tag": tag, "digest": digest or None}


def canonical(ref: str) -> str:
    p = parse(ref)
    return f"{p['registry']}/{p['path']}" + (f":{p['tag']}" if p["tag"] else "") + (f"@{p['digest']}" if p["digest"] else "")


def namespace(registry: str) -> str:
    return NAMESPACES.get(registry) or re.sub(r"[^a-z0-9]+", "-", registry.lower()).strip("-")


def mirror_dest(ref: str) -> str:
    """Repository:tag in the mirror registry (digest-only references get a sha256-<12 hex> tag: pulls by
    digest work whatever the tag, skopeo --all keeps the digest)"""
    p = parse(ref)
    tag = p["tag"] or ("sha256-" + (p["digest"] or "").split(":")[-1][:12])
    return f"{namespace(p['registry'])}/{p['path']}:{tag}"


def hosts_toml(registry: str, mirror_host: str) -> str:
    server = SERVERS.get(registry, f"https://{registry}")
    return (f"# Generated by VM Manager: pulls of {registry} images go to the lab's mirror registry\n"
            f"server = \"{server}\"\n\n"
            f"[host.\"https://{mirror_host}/v2/{namespace(registry)}\"]\n"
            "  capabilities = [\"pull\", \"resolve\"]\n"
            f"  ca = \"{CA_PATH}\"\n"
            "  override_path = true\n")


def registries(images: List[Dict[str, str]]) -> List[str]:
    """Upstream registries with a mirror config on the nodes: the usual four + those of the images"""
    found = list(NAMESPACES)
    for image in images:
        reg = parse(image["source"])["registry"]
        if reg not in found:
            found.append(reg)
    return found


def node_files(dis: Dict[str, Any], ca_pem: str) -> List[Dict[str, Any]]:
    """cloud-init write_files of a node: containerd mirror config + the registry CA (also system-wide:
    the token realm of the registry, curl / podman checks)"""
    host = dis["registry"]
    files = [{"path": f"/etc/containerd/certs.d/{reg}/hosts.toml", "permissions": "0644",
              "content": hosts_toml(reg, host)} for reg in registries(dis.get("images") or [])]
    for path in (CA_PATH, "/usr/local/share/ca-certificates/vmm-registry-ca.crt",
                 "/etc/pki/ca-trust/source/anchors/vmm-registry-ca.crt"):
        files.append({"path": path, "permissions": "0644", "content": ca_pem})
    return files


def push_hosts_toml(vm: str, dis: Dict[str, Any]) -> None:
    """Day 2: a new upstream registry -> its hosts.toml on a running node (containerd reads them per pull)"""
    from app.libvirt_client import libvirt_client
    script = ""
    for reg in registries(dis.get("images") or []):
        b64 = base64.b64encode(hosts_toml(reg, dis["registry"]).encode()).decode()
        script += f"mkdir -p /etc/containerd/certs.d/{reg} && echo {b64} | base64 -d > /etc/containerd/certs.d/{reg}/hosts.toml && "
    out = libvirt_client.agent_exec(vm, "/bin/sh", ["-c", script + "true"], timeout=60)
    if out["exitcode"] != 0:
        raise RuntimeError(f"{vm}: could not write the containerd mirror config: {out['stderr'].strip()}")


# ------------------------------------------------------------------ on the router

def resolve_kubeadm(rtr: str, minor: str, patch: Optional[str]) -> Dict[str, Any]:
    """On the router (internet): the Kubernetes patch (latest of `minor` unless given), the images
    `kubeadm config images list` gives for it, and Flannel's manifest. {version, images, flannel}"""
    from app.libvirt_client import libvirt_client
    from app.services import registry_router as rr
    tools = f"{rr.DATA}/tools"
    want = f"v{patch}" if patch else ""
    script = (
        "set -e\n"
        f"V={want}\n"
        f"[ -n \"$V\" ] || V=$(curl -fsSL --retry 5 https://dl.k8s.io/release/stable-{minor.lstrip('v')}.txt)\n"
        "case \"$V\" in v[0-9]*) ;; *) echo \"no Kubernetes release for " + minor + ": $V\" >&2; exit 3 ;; esac\n"
        f"mkdir -p {tools}\n"
        f"B={tools}/kubeadm-$V\n"
        "if [ ! -x $B ]; then curl -fsSL --retry 5 -o $B.part https://dl.k8s.io/release/$V/bin/linux/amd64/kubeadm"
        " && chmod 755 $B.part && mv $B.part $B; fi\n"
        "echo VERSION=$V\n"
        "$B config images list --kubernetes-version $V 2>/dev/null | sed 's/^/IMAGE=/'\n"
        f"echo FLANNEL=$(curl -fsSL --retry 5 {FLANNEL_MANIFEST} | base64 -w0)\n"
    )
    out = libvirt_client.agent_exec(rtr, "/bin/bash", ["-c", script], timeout=RESOLVE_TIMEOUT)
    if out["exitcode"] != 0:
        raise RuntimeError(f"Could not resolve the Kubernetes images on the router: "
                           f"{(out['stderr'] or out['stdout']).strip()[-800:]}")
    version, images, flannel = None, [], ""
    for line in out["stdout"].splitlines():
        key, _, value = line.partition("=")
        if key == "VERSION":
            version = value.strip()
        elif key == "IMAGE" and value.strip():
            images.append(value.strip())
        elif key == "FLANNEL":
            flannel = value.strip()
    if not version or not images:
        raise RuntimeError(f"Unexpected output while listing the Kubernetes images: {out['stdout'][-500:]}")
    if not flannel:
        raise RuntimeError(f"Could not download the Flannel manifest ({FLANNEL_MANIFEST}) on the router")
    manifest = base64.b64decode(flannel).decode()
    images += flannel_images(manifest)
    return {"version": version, "images": images, "flannel": flannel}


def flannel_images(manifest: str) -> List[str]:
    found: List[str] = []
    for m in re.finditer(r"^\s*image:\s*['\"]?([^\s'\"]+)", manifest, re.M):
        if m.group(1) not in found:
            found.append(m.group(1))
    return found


def mirror(group: Any, sources: List[str], progress: Any, label: str) -> Tuple[List[Dict[str, str]], List[str]]:
    """Copy `sources` into the group's registry: ([{source, mirror}], failed sources)"""
    from app.services import registry_images
    from app.services import registry_service as rs
    host = rs._hosts(rs._spec(group))[0]
    pairs: List[Tuple[str, str]] = []
    for src in sources:
        c = canonical(src)
        if all(c != p[0] for p in pairs):
            pairs.append((c, mirror_dest(c)))
    failed = registry_images.copy_list(group, pairs, progress, label)
    return [{"source": s, "mirror": f"{host}/{d}"} for s, d in pairs if s not in failed], failed
