"""Router side of the mirror registry: the script pushed to EL routers (router_service) and driven by
registry_service through the guest agent.

    vmm-registry.sh setup        mount the registry disk (xfs), install podman, download mirror-registry and
                                 oc-mirror (the router has internet), make the CA + server certificate,
                                 install Quay, trust the CA, check /health/instance. Run detached
                                 (systemd-run unit vmm-registry-setup), progress in $STATE/phase.
    vmm-registry.sh apply        on every config push: /etc/hosts entry, start / stop the Quay units
    vmm-registry.sh status       key=value lines for the app
    vmm-registry.sh mirror <id>  oc-mirror v2 run of $DATA/runs/<id>/isc.yaml (detached unit vmm-mirror-<id>)

Quay's SERVER_HOSTNAME is <uplink_ip>:<port>: its token realm (WWW-Authenticate) is built from it, and
that address works from the host (pinned uplink), WireGuard devices and the group network alike (it is
the router's own address: never forwarded, so blocked egress doesn't affect it). Images are referenced
as registry.<domain>:<port>/... (the certificate covers both names and the LAN address).
"""
from typing import Dict

from app.schemas.group import GroupSpec, REGISTRY_DISK_SERIAL

SCRIPT = "/usr/local/libexec/vmm-registry.sh"
ENV_FILE = "/etc/vmm-registry/registry.env"
CREDENTIALS = "/etc/vmm-registry/credentials"   # pushed by registry_service (never rendered)
DATA = "/var/lib/vmm-registry"                  # registry disk mount point
STATE = "/var/lib/vmm-router/registry"          # phase / error (root disk)
SETUP_UNIT = "vmm-registry-setup"
SETUP_LOG = "/var/log/vmm-registry-setup.log"
MIRROR_RUNS = f"{DATA}/runs"
MIRROR_REGISTRY_URL = "https://mirror.openshift.com/pub/cgw/mirror-registry/latest/mirror-registry-amd64.tar.gz"
OC_MIRROR_URL = "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/oc-mirror.rhel9.tar.gz"
QUAY_UNITS = "quay-pod quay-redis quay-app"

SCRIPT_TEXT = r"""#!/bin/bash
# Generated by VM Manager: mirror registry on the group router (docs/disconnected.md)
set -o pipefail
ENV=@ENV@
CRED=@CRED@
DATA=@DATA@
STATE=@STATE@
DISK=/dev/disk/by-id/virtio-@SERIAL@
MR_URL=@MR_URL@
OCM_URL=@OCM_URL@
UNITS="@UNITS@"
[ -f $ENV ] && . $ENV
mkdir -p $STATE

phase() { echo "$1" > $STATE/phase; echo "== $(date -Is) $1"; }
fail() { echo "$*" | tr '\n' ' ' | head -c 1500 > $STATE/error; phase failed; exit 1; }
installed() { [ -f /etc/systemd/system/quay-app.service ]; }
cacert() { echo $DATA/certs/ca.crt; }
healthy() {
    curl -sf -o /dev/null --max-time 5 --cacert "$(cacert)" \
        --resolve "$VMM_REG_HOST:$VMM_REG_PORT:127.0.0.1" "https://$VMM_REG_HOST:$VMM_REG_PORT/health/instance"
}

mount_disk() {
    [ -b $DISK ] || { echo "the registry disk ($DISK) is not attached"; return 1; }
    mkdir -p $DATA
    if ! mountpoint -q $DATA; then
        blkid $DISK >/dev/null 2>&1 || mkfs.xfs -q -L vmm-registry $DISK || return 1
        uuid=$(blkid -s UUID -o value $DISK)
        grep -q "UUID=$uuid " /etc/fstab || echo "UUID=$uuid $DATA xfs defaults,nofail 0 0" >> /etc/fstab
        systemctl daemon-reload
        mount $DATA || return 1
    fi
    xfs_growfs -d $DATA >/dev/null 2>&1  # the disk was enlarged
    return 0
}

hosts_entry() {
    sed -i "/[[:space:]]$VMM_REG_HOST\$/d" /etc/hosts
    echo "$VMM_REG_LAN_IP $VMM_REG_HOST" >> /etc/hosts
}

setup() {
    exec >> @SETUP_LOG@ 2>&1
    # systemd-run units have no HOME / USER: mirror-registry keeps its SSH key in ~/.ssh and runs its
    # ansible over SSH as $USER@$(hostname)
    export HOME=/root USER=root
    chmod 600 @SETUP_LOG@
    rm -f $STATE/error
    [ "$VMM_REG_ENABLED" = 1 ] || fail "the registry is not enabled in the group spec"
    [ -s "$CRED" ] || fail "registry credentials missing (pushed by the app)"
    . $CRED
    [ -n "$VMM_REG_UPLINK_IP" ] || fail "the router's uplink address is not known yet"
    have=$(awk '/MemTotal/ {print int($2 / 1024)}' /proc/meminfo)
    if [ "$have" -lt $((VMM_REG_MEMORY_MB * 85 / 100)) ]; then
        echo "the router has $have MiB of RAM, the registry needs $VMM_REG_MEMORY_MB MiB: restart the router" > $STATE/error
        phase restart-required
        exit 1
    fi
    phase disk
    mount_disk || fail "could not mount the registry disk"
    phase packages
    rpm -q podman openssl tar skopeo >/dev/null || dnf -y -q install podman openssl tar skopeo || fail "dnf install podman openssl tar skopeo failed"
    # podman's storage on the registry disk: Quay's images alone are ~3 GB unpacked (the root disk is 10 GiB)
    if ! grep -q "^graphroot = \"$DATA/containers\"" /etc/containers/storage.conf 2>/dev/null; then
        mkdir -p $DATA/containers
        semanage fcontext -a -e /var/lib/containers $DATA/containers 2>/dev/null
        restorecon -R $DATA/containers
        sed -i "s|^graphroot = .*|graphroot = \"$DATA/containers\"|" /etc/containers/storage.conf
        rm -rf /var/lib/containers/storage
    fi
    export TMPDIR=$DATA/tmp
    phase download
    mkdir -p $DATA/tools $DATA/tmp
    if [ ! -x $DATA/tools/mirror-registry/mirror-registry ]; then
        curl -fsSL --retry 5 --retry-delay 5 -o $DATA/tools/mirror-registry.tar.gz.part "$MR_URL" \
            || fail "could not download mirror-registry from $MR_URL"
        rm -rf $DATA/tools/mirror-registry && mkdir -p $DATA/tools/mirror-registry
        tar -xzf $DATA/tools/mirror-registry.tar.gz.part -C $DATA/tools/mirror-registry || fail "mirror-registry archive is damaged"
        rm -f $DATA/tools/mirror-registry.tar.gz.part
    fi
    if [ ! -x /usr/local/bin/oc-mirror ]; then
        curl -fsSL --retry 5 --retry-delay 5 -o $DATA/tools/oc-mirror.tar.gz "$OCM_URL" \
            || fail "could not download oc-mirror from $OCM_URL"
        tar -xzf $DATA/tools/oc-mirror.tar.gz -C /usr/local/bin oc-mirror && chmod 755 /usr/local/bin/oc-mirror \
            || fail "oc-mirror archive is damaged"
        rm -f $DATA/tools/oc-mirror.tar.gz
    fi
    phase certificate
    C=$DATA/certs
    mkdir -p $C && chmod 700 $C
    if [ ! -s $C/ca.crt ]; then
        openssl req -x509 -newkey rsa:4096 -nodes -sha256 -days 3650 -keyout $C/ca.key -out $C/ca.crt \
            -subj "/CN=VM Manager registry CA $VMM_REG_HOST" \
            -addext "basicConstraints=critical,CA:TRUE" -addext "keyUsage=critical,keyCertSign,cRLSign" \
            || fail "could not create the registry CA"
    fi
    sans="DNS:$VMM_REG_HOST,IP:$VMM_REG_LAN_IP,IP:$VMM_REG_UPLINK_IP"
    renewed=0
    if [ "$(cat $C/sans 2>/dev/null)" != "$sans" ] || [ ! -s $C/ssl.crt ]; then
        printf 'subjectAltName=%s\nextendedKeyUsage=serverAuth\nkeyUsage=critical,digitalSignature,keyEncipherment\nbasicConstraints=CA:FALSE\n' \
            "$sans" > $C/ssl.ext
        openssl req -newkey rsa:2048 -nodes -sha256 -keyout $C/ssl.key -out $C/ssl.csr -subj "/CN=$VMM_REG_HOST" \
            && openssl x509 -req -sha256 -days 3650 -in $C/ssl.csr -CA $C/ca.crt -CAkey $C/ca.key -CAcreateserial \
                -out $C/ssl.crt -extfile $C/ssl.ext || fail "could not create the registry certificate"
        echo "$sans" > $C/sans
        renewed=1
    fi
    cp $C/ca.crt /etc/pki/ca-trust/source/anchors/vmm-registry-ca.crt && update-ca-trust
    hosts_entry
    if ! installed; then
        phase install
        cd $DATA/tools/mirror-registry || fail "mirror-registry is missing"
        # its ansible logs in over SSH as root@localhost with this key (made here: idempotent across retries)
        mkdir -p /root/.ssh && chmod 700 /root/.ssh
        [ -s /root/.ssh/quay_installer.pub ] || { rm -f /root/.ssh/quay_installer; ssh-keygen -q -t ed25519 -N '' -f /root/.ssh/quay_installer; }
        grep -qF "$(cut -d' ' -f2 /root/.ssh/quay_installer.pub)" /root/.ssh/authorized_keys 2>/dev/null \
            || cat /root/.ssh/quay_installer.pub >> /root/.ssh/authorized_keys
        chmod 600 /root/.ssh/authorized_keys && restorecon -R /root/.ssh
        # quayHostname = SERVER_HOSTNAME = token realm: the uplink address (see registry_router.py)
        ./mirror-registry install --quayHostname "$VMM_REG_UPLINK_IP:$VMM_REG_PORT" \
            --quayRoot $DATA/quay-install --quayStorage $DATA/quay-storage --sqliteStorage $DATA/sqlite-storage \
            --sslCert $C/ssl.crt --sslKey $C/ssl.key \
            --initUser "$VMM_REG_USER" --initPassword "$VMM_REG_PASSWORD" 2>&1 \
            | sed -u "s/$VMM_REG_PASSWORD/********/g"
        [ $? = 0 ] && installed || fail "mirror-registry install failed (see @SETUP_LOG@ on the router)"
        renewed=0
    fi
    for u in $UNITS; do
        mkdir -p /etc/systemd/system/$u.service.d
        printf '[Unit]\nRequiresMountsFor=%s\n' $DATA > /etc/systemd/system/$u.service.d/vmm-registry.conf
    done
    systemctl daemon-reload
    cfg=$DATA/quay-install/quay-config/config.yaml
    restart=0
    # Mirrored repositories are readable without credentials (lab members pull with plain podman); pushing
    # needs the app's credentials
    if ! grep -q '^CREATE_PRIVATE_REPO_ON_PUSH: false' $cfg; then
        sed -i '/^CREATE_PRIVATE_REPO_ON_PUSH:/d' $cfg && echo 'CREATE_PRIVATE_REPO_ON_PUSH: false' >> $cfg
        restart=1
    fi
    if [ $renewed = 1 ]; then
        phase certificate-update
        cp $C/ssl.crt $DATA/quay-install/quay-config/ssl.cert && cp $C/ssl.key $DATA/quay-install/quay-config/ssl.key
        sed -i "s/^SERVER_HOSTNAME:.*/SERVER_HOSTNAME: $VMM_REG_UPLINK_IP:$VMM_REG_PORT/" $cfg
        restart=1
    fi
    [ $restart = 1 ] && systemctl restart quay-app
    systemctl enable -q --now $UNITS
    phase starting
    for i in $(seq 60); do healthy && break; sleep 5; done
    healthy || fail "Quay does not answer on https://$VMM_REG_HOST:$VMM_REG_PORT/health/instance"
    phase ready
}

apply() {
    if [ "$VMM_REG_ENABLED" = 1 ]; then
        hosts_entry
        if installed && mountpoint -q $DATA; then systemctl enable -q --now $UNITS || true; fi
    elif installed; then
        systemctl disable -q --now $UNITS 2>/dev/null
        [ "$(cat $STATE/phase 2>/dev/null)" = ready ] && phase disabled
    fi
    true
}

status() {
    echo "phase=$(cat $STATE/phase 2>/dev/null || echo none)"
    echo "error=$(cat $STATE/error 2>/dev/null)"
    echo "setup_active=$(systemctl is-active @SETUP_UNIT@ 2>/dev/null)"
    echo "installed=$(installed && echo 1 || echo 0)"
    echo "app=$(systemctl is-active quay-app 2>/dev/null)"
    echo "healthy=$( [ "$VMM_REG_ENABLED" = 1 ] && installed && healthy && echo 1 || echo 0)"
    echo "memory_mb=$(awk '/MemTotal/ {print int($2 / 1024)}' /proc/meminfo)"
    echo "disk=$( [ -b $DISK ] && echo 1 || echo 0)"
    [ -f $DATA/tools/mirror-registry.tar.gz.part ] && echo "download=$(stat -c %s $DATA/tools/mirror-registry.tar.gz.part)"
    mountpoint -q $DATA && df -B1 --output=size,used $DATA | awk 'NR == 2 {print "disk_total=" $1; print "disk_used=" $2}'
    for u in $(systemctl list-units --plain --no-legend 'vmm-mirror-*.service' | awk '$3 == "active" {print $1}'); do
        echo "mirror_active=${u#vmm-mirror-}"
    done
    [ -s $DATA/certs/ca.crt ] && echo "ca=$(base64 -w0 $DATA/certs/ca.crt)"
    true
}

mirror() {
    id=$1
    R=$DATA/runs/$id
    A=/run/vmm-mirror-$id
    trap 'rm -rf $A' EXIT
    exec > $R/log 2>&1
    rm -f $R/rc
    export TMPDIR=$DATA/tmp HOME=/root
    mkdir -p $TMPDIR $DATA/cache
    /usr/local/bin/oc-mirror --v2 -c $R/isc.yaml --workspace file://$R/workspace \
        "docker://$VMM_REG_HOST:$VMM_REG_PORT" --cache-dir $DATA/cache --authfile $A/auth.json \
        --image-timeout 30m --retry-times 5
    rc=$?
    # oc-mirror exits 0 even when some images failed: they are listed in working-dir/logs/mirroring_errors_*
    if [ $rc = 0 ] && ls $R/workspace/working-dir/logs/mirroring_errors_* >/dev/null 2>&1; then rc=3; fi
    echo $rc > $R/rc
}

copy() {
    id=$1
    R=$DATA/copies/$id
    A=/run/vmm-copy-$id
    trap 'rm -rf $A' EXIT
    exec > $R/log 2>&1
    rm -f $R/rc
    rpm -q skopeo >/dev/null || dnf -y -q install skopeo || { echo 1 > $R/rc; exit 1; }
    src=$(sed -n 1p $R/job)
    dest=$(sed -n 2p $R/job)
    export TMPDIR=$DATA/tmp
    mkdir -p $TMPDIR
    skopeo copy --all --retry-times 3 --authfile $A/auth.json "docker://$src" "docker://$dest"
    echo $? > $R/rc
}

case "$1" in
    setup) setup ;;
    apply) apply ;;
    status) status ;;
    mirror) mirror "$2" ;;
    copy) copy "$2" ;;
    *) echo "usage: $0 setup|apply|status|mirror <id>|copy <id>"; exit 2 ;;
esac
"""


def script() -> str:
    text = SCRIPT_TEXT
    for key, value in (("@ENV@", ENV_FILE), ("@CRED@", CREDENTIALS), ("@DATA@", DATA), ("@STATE@", STATE),
                       ("@SERIAL@", REGISTRY_DISK_SERIAL), ("@MR_URL@", MIRROR_REGISTRY_URL),
                       ("@OCM_URL@", OC_MIRROR_URL), ("@UNITS@", QUAY_UNITS), ("@SETUP_LOG@", SETUP_LOG),
                       ("@SETUP_UNIT@", SETUP_UNIT)):
        text = text.replace(key, value)
    return text


def env_file(spec: GroupSpec) -> str:
    reg = spec.router.registry
    return "".join(f"{k}={v}\n" for k, v in (
        ("VMM_REG_ENABLED", "1" if reg.enabled else "0"),
        ("VMM_REG_HOST", f"registry.{spec.domain}"),
        ("VMM_REG_PORT", reg.port),
        ("VMM_REG_LAN_IP", spec.router.ip or ""),
        ("VMM_REG_UPLINK_IP", spec.router.uplink_ip or ""),
        ("VMM_REG_MEMORY_MB", reg.memory_mb),
    ))


def files(spec: GroupSpec) -> Dict[str, str]:
    """Router files for the registry: only once it has been enabled (hostname assigned)"""
    reg = spec.router.registry
    if not reg.enabled and not reg.hostname:
        return {}
    return {SCRIPT: script(), ENV_FILE: env_file(spec)}


def apply_command(spec: GroupSpec) -> str:
    reg = spec.router.registry
    if not reg.enabled and not reg.hostname:
        return ""
    return f"{{ bash {SCRIPT} apply; true; }}"
