"""Router config generation for lab groups

A RouterBackend turns a (normalized) GroupSpec into the router VM's cloud-init
(user-data + network-config) and the list of config files that depend on the
spec. Those files are re-rendered and pushed through the QEMU guest agent when
the spec changes, then `apply_command` reloads the services.

Flavours: "el" (EL cloud image + dnsmasq + nftables) is implemented; "vyos" is
reserved. New flavours (VyOS, OPNsense, OpenWrt) implement the same interface.
v2 spec blocks (bgp, wireguard, vlans) are rejected by validate() until a
backend renders them (FRR, wg0.conf, NM VLAN keyfiles for "el").
"""
import ipaddress
from dataclasses import dataclass, field
from typing import Dict, List

import yaml

from app.schemas.group import DNSRecord, GroupSpec
from app.services.cloud_image_service import cloud_image_service

DNSMASQ_CONF = "/etc/dnsmasq.d/group.conf"
NFT_CONF = "/etc/nftables/vmm-group.nft"
HAPROXY_CONF = "/etc/haproxy/haproxy.cfg"
# First-boot swap file: dnf (package metadata) is the router's only memory peak; with it a small
# router never OOMs while installing packages (see ROUTER_MEMORY_DEFAULT in schemas/group.py)
SWAP_SIZE = "1G"
STATE_DIR = "/var/lib/vmm-router"


@dataclass
class RenderedRouter:
    user_data: str
    network_config: str
    files: Dict[str, str] = field(default_factory=dict)  # spec-dependent files, pushed on updates
    apply_command: str = ""                              # /bin/sh -c script run after pushing files


class RouterBackend:
    flavour = ""

    def validate(self, spec: GroupSpec) -> None:
        """Raise ValueError for spec features this router can't do (yet)"""
        raise NotImplementedError

    def render(self, spec: GroupSpec) -> RenderedRouter:
        """spec must be normalized (router IP/MACs, member IPs/MACs, DHCP range assigned)"""
        raise NotImplementedError


def record_fqdn(name: str, domain: str) -> str:
    """'api.ocp' -> 'api.ocp.<domain>', 'host.example.' -> 'host.example'"""
    return name[:-1] if name.endswith(".") else f"{name}.{domain}"


class ELRouterBackend(RouterBackend):
    """Enterprise Linux cloud image (AlmaLinux / Rocky / CentOS Stream / RHEL):
    dnsmasq (DHCP + DNS), nftables (NAT), NetworkManager (via cloud-init network-config)."""

    flavour = "el"

    def validate(self, spec: GroupSpec) -> None:
        router = spec.router
        unsupported = [label for label, used in (
            ("BGP (router.bgp)", router.bgp is not None),
            ("WireGuard (router.wireguard)", router.wireguard is not None),
            ("VLANs (router.vlans)", bool(router.vlans)),
        ) if used]
        if unsupported:
            raise ValueError(f"{', '.join(unsupported)}: not supported yet by the '{self.flavour}' router")
        if not spec.uplink:
            raise ValueError("A group without uplink is not supported yet: the 'el' router installs "
                             "dnsmasq and nftables from the internet at first boot")

    # spec-dependent files

    def dnsmasq_conf(self, spec: GroupSpec) -> str:
        net = ipaddress.IPv4Network(spec.cidr)
        rip, domain = spec.router.ip, spec.domain
        lines = [
            f"# Generated by VM Manager from the spec of group '{spec.name}': local changes are overwritten.",
            f"listen-address=127.0.0.1,{rip}",
            "bind-dynamic",
            "no-hosts",  # the router's /etc/hosts maps its own fqdn to loopback
            "domain-needed",
            "bogus-priv",
            f"domain={domain}",
            f"local=/{domain}/",
            f"dhcp-range={spec.dhcp.start},{spec.dhcp.end},{net.netmask},12h",
            f"dhcp-option=option:router,{rip}",
            f"dhcp-option=option:dns-server,{rip}",
            f"dhcp-option=option:domain-search,{domain}",
            "dhcp-authoritative",
            "log-dhcp",
        ]
        if spec.router.dns.forwarders:
            lines.append("no-resolv")
            lines += [f"server={f}" for f in spec.router.dns.forwarders]
        lines += ["", "# router", f"host-record=router.{domain},router,{rip}", "", "# members"]
        for m in spec.members:
            lines.append(f"dhcp-host={m.mac},{m.ip},{m.name}")
            lines.append(f"host-record={m.name}.{domain},{m.name},{m.ip}")
        if spec.reservations:
            lines += ["", "# reserved hosts (not members)"]
        for r in spec.reservations:
            if r.owner:
                lines.append(f"# {r.owner}")
            lines.append(f"dhcp-host={r.mac},{r.ip},{r.name}")
            lines.append(f"host-record={r.name}.{domain},{r.name},{r.ip}")
        lines += ["", "# records"]
        lines += [self._record(r, domain) for r in spec.router.dns.records]
        return "\n".join(lines) + "\n"

    @staticmethod
    def _record(record: DNSRecord, domain: str) -> str:
        if record.name.startswith("*."):
            # address= matches the name and every name below it
            return f"address=/{record_fqdn(record.name[2:], domain)}/{record.a}"
        fqdn = record_fqdn(record.name, domain)
        if record.a:
            return f"host-record={fqdn},{record.a}"
        return f"cname={fqdn},{record_fqdn(record.cname, domain)}"

    def nft_conf(self, spec: GroupSpec) -> str:
        nat = (f"        ip saddr {spec.cidr} ip daddr != {spec.cidr} masquerade\n" if spec.uplink else "")
        return (
            "#!/usr/sbin/nft -f\n"
            f"# Generated by VM Manager for group '{spec.name}': local changes are overwritten.\n"
            "table ip vmm_group\n"
            "delete table ip vmm_group\n"
            "table ip vmm_group {\n"
            "    chain forward {\n"
            "        type filter hook forward priority filter; policy accept;\n"
            "    }\n"
            "    chain postrouting {\n"
            "        type nat hook postrouting priority srcnat; policy accept;\n"
            f"{nat}"
            "    }\n"
            "}\n"
        )

    def haproxy_conf(self, spec: GroupSpec) -> str:
        lines = [
            f"# Generated by VM Manager for group '{spec.name}': local changes are overwritten.",
            "global",
            "    log /dev/log local0",
            "    maxconn 4000",
            "",
            "defaults",
            "    mode tcp",
            "    log global",
            "    option tcplog",
            "    option dontlognull",
            "    retries 3",
            "    option redispatch",  # a backend that just died: retry the connection on another one
            "    timeout connect 5s",
            # long-lived watches (kubectl get -w, controllers) go through the load balancer
            "    timeout client 1h",
            "    timeout server 1h",
            "    timeout check 3s",
            "    default-server inter 3s fall 2 rise 2",
        ]
        for lb in spec.load_balancers:
            lines += ["", f"# {lb.owner or lb.name}", f"listen {lb.name}", f"    bind *:{lb.port}",
                      f"    mode {lb.mode}", "    balance roundrobin"]
            lines += [f"    server {lb.name}-{i} {backend} check" for i, backend in enumerate(lb.backends)]
        return "\n".join(lines) + "\n"

    def apply_command(self, spec: GroupSpec) -> str:
        base = (f"restorecon -R /etc/dnsmasq.d /etc/nftables 2>/dev/null; "
                f"nft -f {NFT_CONF} && systemctl restart dnsmasq && systemctl is-active dnsmasq")
        if not spec.load_balancers:
            return base + " && { systemctl disable --now haproxy >/dev/null 2>&1; true; }"
        # Routers created before load balancers existed have no haproxy yet: install it once.
        # haproxy_connect_any lets haproxy bind / connect to any port (-P: persistent, set only once
        # since it rebuilds the policy)
        return (base + " && { rpm -q haproxy >/dev/null || dnf -y -q install haproxy; }"
                " && { getsebool haproxy_connect_any 2>/dev/null | grep -q 'on$'"
                " || setsebool -P haproxy_connect_any 1 || true; }"
                f" && {{ restorecon {HAPROXY_CONF} 2>/dev/null; haproxy -c -q -f {HAPROXY_CONF}; }}"
                " && systemctl enable -q haproxy && systemctl reload-or-restart haproxy"
                " && systemctl is-active haproxy")

    def files(self, spec: GroupSpec) -> Dict[str, str]:
        """Spec-dependent files, re-rendered and pushed on every change"""
        return {DNSMASQ_CONF: self.dnsmasq_conf(spec), NFT_CONF: self.nft_conf(spec),
                HAPROXY_CONF: self.haproxy_conf(spec)}

    def network_config(self, spec: GroupSpec) -> str:
        net = ipaddress.IPv4Network(spec.cidr)
        ethernets: Dict[str, Dict] = {}
        if spec.uplink:
            ethernets["uplink"] = {"match": {"macaddress": spec.router.uplink_mac}, "dhcp4": True}
        ethernets["lan"] = {
            "match": {"macaddress": spec.router.lan_mac},
            "dhcp4": False,
            "addresses": [f"{spec.router.ip}/{net.prefixlen}"],
        }
        return yaml.safe_dump({"version": 2, "ethernets": ethernets}, sort_keys=False)

    def render(self, spec: GroupSpec) -> RenderedRouter:
        self.validate(spec)
        ci = spec.cloud_init
        config = cloud_image_service.build_cloud_config(
            hostname="router", username=ci.username, password=ci.password,
            ssh_keys=[k.strip() for k in ci.ssh_keys if k.strip()], keyboard=ci.keyboard,
            fqdn=f"router.{spec.domain}")
        # haproxy is always installed (same dnf run, ~10 MB on disk) but only enabled when the spec
        # has load balancers: adding one later needs no dnf run on a live, memory-tight router
        config["packages"] = ["qemu-guest-agent", "dnsmasq", "nftables", "policycoreutils-python-utils", "haproxy"]
        # cc_mounts runs before package installation: the swap file absorbs dnf's metadata peak
        config["swap"] = {"filename": "/swapfile", "size": SWAP_SIZE, "maxsize": SWAP_SIZE}

        files = self.files(spec)
        static_files = {
            # EL's qemu-ga only allows a few commands (no guest-exec / guest-file-*): run it unrestricted
            "/etc/systemd/system/qemu-guest-agent.service.d/vmm-router.conf": (
                "[Service]\nExecStart=\n"
                "ExecStart=/usr/bin/qemu-ga --method=virtio-serial --path=/dev/virtio-ports/org.qemu.guest_agent.0\n"),
            "/etc/dnsmasq.conf": "user=dnsmasq\ngroup=dnsmasq\nconf-dir=/etc/dnsmasq.d,.rpmnew,.rpmsave,.rpmorig\n",
            "/etc/sysconfig/nftables.conf": f'include "{NFT_CONF}"\n',
            "/etc/sysctl.d/90-vmm-router.conf": "net.ipv4.ip_forward = 1\n",
        }
        config["write_files"] = [{"path": p, "content": c, "permissions": "0644"}
                                 for p, c in {**static_files, **files}.items()]
        config["runcmd"] = config.get("runcmd", []) + [
            "systemctl daemon-reload",
            "systemctl restart qemu-guest-agent",
            # SELinux stays enforcing; only the guest agent's domain is permissive, so config pushes work
            "semanage permissive -a virt_qemu_ga_t || setsebool -P virt_qemu_ga_run_unconfined on || true",
            "systemctl disable --now firewalld 2>/dev/null || true",
            "sysctl --system",
            "restorecon -R /etc/dnsmasq.conf /etc/dnsmasq.d /etc/nftables /etc/sysconfig/nftables.conf || true",
            "systemctl enable nftables && systemctl restart nftables",
            "systemctl enable dnsmasq && systemctl restart dnsmasq",
            *([f"{self.apply_command(spec)} || true"] if spec.load_balancers else []),
            f"mkdir -p {STATE_DIR}",
            f"if systemctl is-active -q dnsmasq; then touch {STATE_DIR}/ready; "
            f"else systemctl status dnsmasq > {STATE_DIR}/failed 2>&1; fi",
        ]
        user_data = "#cloud-config\n" + yaml.safe_dump(config, sort_keys=False)
        return RenderedRouter(user_data=user_data, network_config=self.network_config(spec), files=files,
                              apply_command=self.apply_command(spec))


class VyOSRouterBackend(RouterBackend):
    """Reserved: VyOS config commands via cloud-init vyos_config_commands (future-features §2.2)"""

    flavour = "vyos"

    def validate(self, spec: GroupSpec) -> None:
        raise ValueError("Router flavour 'vyos' is not supported yet: use 'el'")

    def render(self, spec: GroupSpec) -> RenderedRouter:
        self.validate(spec)
        raise NotImplementedError


BACKENDS: Dict[str, RouterBackend] = {b.flavour: b for b in (ELRouterBackend(), VyOSRouterBackend())}


def get_backend(flavour: str) -> RouterBackend:
    try:
        return BACKENDS[flavour]
    except KeyError:
        raise ValueError(f"Unknown router flavour '{flavour}' (known: {', '.join(BACKENDS)})")


# Router images, in order of preference, when the spec doesn't name one
EL_IMAGES: List[str] = ["almalinux-9", "almalinux-10", "rocky-9", "centos-9-stream", "centos-10-stream"]
