"""Router config generation for lab groups

A RouterBackend turns a (normalized) GroupSpec into the router VM's cloud-init
(user-data + network-config) and the list of config files that depend on the
spec. Those files are re-rendered and pushed through the QEMU guest agent when
the spec changes, then `apply_command` reloads the services.

Flavours: "el" (EL cloud image + dnsmasq + nftables + WireGuard + FRR/BGP) is implemented;
"vyos" is reserved. New flavours (VyOS, OPNsense, OpenWrt) implement the same interface.
The vlans block is rejected by validate() until a backend renders it (NM VLAN keyfiles for "el").
"""
import ipaddress
from dataclasses import dataclass, field
from typing import Dict, List

import yaml

from app.schemas.group import DNSRecord, GroupSpec
from app.services import registry_router
from app.services.cloud_image_service import cloud_image_service

DNSMASQ_CONF = "/etc/dnsmasq.d/group.conf"
NFT_CONF = "/etc/nftables/vmm-group.nft"
HAPROXY_CONF = "/etc/haproxy/haproxy.cfg"
WG_CONF = "/etc/wireguard/wg0.conf"
WG_KEY = "/etc/wireguard/private.key"
FRR_CONF = "/etc/frr/frr.conf"
PRUNE_LEASES = "/usr/local/libexec/vmm-prune-leases.sh"
# Run while dnsmasq is stopped: drop the leases whose address is now reserved for another MAC (e.g. a
# cluster node re-created with a new MAC on the same address). Otherwise dnsmasq keeps that address
# for the old lease (12 h) and gives the new VM a dynamic one.
_PRUNE_LEASES_SH = r"""#!/bin/sh
# Generated by VM Manager: drop leases of reserved addresses held by another MAC
CONF=/etc/dnsmasq.d/group.conf
LEASES=/var/lib/dnsmasq/dnsmasq.leases
TMP=/run
[ -f "$LEASES" ] || exit 0
awk -F'[=,]' '/^dhcp-host=/ {print tolower($2), $3}' "$CONF" > "$TMP/vmm-reserved" || exit 1
awk 'NR == FNR {mac[$2] = $1; next} !($3 in mac) || mac[$3] == tolower($2)' "$TMP/vmm-reserved" "$LEASES" > "$TMP/vmm-leases"
cmp -s "$LEASES" "$TMP/vmm-leases" || cat "$TMP/vmm-leases" > "$LEASES"
rm -f "$TMP/vmm-reserved" "$TMP/vmm-leases"
"""
# First-boot swap file: dnf (package metadata) is the router's only memory peak; with it a small
# router never OOMs while installing packages (see ROUTER_MEMORY_DEFAULT in schemas/group.py)
SWAP_SIZE = "1G"
STATE_DIR = "/var/lib/vmm-router"


@dataclass
class RenderedRouter:
    user_data: str
    network_config: str
    files: Dict[str, str] = field(default_factory=dict)  # spec-dependent files, pushed on updates
    apply_command: str = ""                              # /bin/sh -c script run after pushing files


class RouterBackend:
    flavour = ""

    def validate(self, spec: GroupSpec) -> None:
        """Raise ValueError for spec features this router can't do (yet)"""
        raise NotImplementedError

    def render(self, spec: GroupSpec) -> RenderedRouter:
        """spec must be normalized (router IP/MACs, member IPs/MACs, DHCP range assigned)"""
        raise NotImplementedError


def record_fqdn(name: str, domain: str) -> str:
    """'api.ocp' -> 'api.ocp.<domain>', 'host.example.' -> 'host.example'"""
    return name[:-1] if name.endswith(".") else f"{name}.{domain}"


class ELRouterBackend(RouterBackend):
    """Enterprise Linux cloud image (AlmaLinux / Rocky / CentOS Stream / RHEL):
    dnsmasq (DHCP + DNS), nftables (NAT), NetworkManager (via cloud-init network-config)."""

    flavour = "el"

    def validate(self, spec: GroupSpec) -> None:
        router = spec.router
        unsupported = [label for label, used in (
            ("VLANs (router.vlans)", bool(router.vlans)),
        ) if used]
        if unsupported:
            raise ValueError(f"{', '.join(unsupported)}: not supported yet by the '{self.flavour}' router")
        if not spec.uplink:
            raise ValueError("A group without uplink is not supported yet: the 'el' router installs "
                             "dnsmasq and nftables from the internet at first boot")

    # spec-dependent files

    def dnsmasq_conf(self, spec: GroupSpec) -> str:
        net = ipaddress.IPv4Network(spec.cidr)
        rip, domain = spec.router.ip, spec.domain
        wg = self._wg(spec)
        lines = [
            f"# Generated by VM Manager from the spec of group '{spec.name}': local changes are overwritten.",
            # + the WireGuard tunnel address: the lab zone resolves from remote devices
            f"listen-address=127.0.0.1,{rip}" + (f",{wg.router_ip()}" if wg else ""),
            "bind-dynamic",
            "no-hosts",  # the router's /etc/hosts maps its own fqdn to loopback
            "domain-needed",
            "bogus-priv",
            f"domain={domain}",
            f"local=/{domain}/",
            f"dhcp-range={spec.dhcp.start},{spec.dhcp.end},{net.netmask},12h",
            f"dhcp-option=option:router,{rip}",
            f"dhcp-option=option:dns-server,{rip}",
            f"dhcp-option=option:domain-search,{domain}",
            f"dhcp-option=option:ntp-server,{rip}",  # chrony on the router (ntp_command)
            "dhcp-authoritative",
            "log-dhcp",
        ]
        if spec.router.dns.forwarders:
            lines.append("no-resolv")
            lines += [f"server={f}" for f in spec.router.dns.forwarders]
        lines += ["", "# router", f"host-record=router.{domain},router,{rip}"]
        if spec.router.registry.enabled:
            lines += ["# mirror registry (on the router)", f"host-record=registry.{domain},{rip}"]
        lines += ["", "# members"]
        for m in spec.members:
            lines.append(f"dhcp-host={m.mac},{m.ip},{m.name}")
            lines.append(f"host-record={m.name}.{domain},{m.name},{m.ip}")
        if spec.reservations:
            lines += ["", "# reserved hosts (not members)"]
        for r in spec.reservations:
            if r.owner:
                lines.append(f"# {r.owner}")
            lines.append(f"dhcp-host={r.mac},{r.ip},{r.name}")
            lines.append(f"host-record={r.name}.{domain},{r.name},{r.ip}")
        lines += ["", "# records"]
        lines += [self._record(r, domain) for r in spec.router.dns.records]
        lines += self._dhcp_host_lines(spec)
        return "\n".join(lines) + "\n"

    @staticmethod
    def _dhcp_host_lines(spec: GroupSpec) -> List[str]:
        """Static reservations of non-member machines (spec.dhcp_hosts)"""
        if not spec.dhcp_hosts:
            return []
        lines = ["", "# reservations"]
        for h in spec.dhcp_hosts:
            if h.hostname:
                lines.append(f"dhcp-host={h.mac},{h.ip},{h.hostname}")
                lines.append(f"host-record={h.hostname}.{spec.domain},{h.hostname},{h.ip}")
            else:
                lines.append(f"dhcp-host={h.mac},{h.ip}")
        return lines

    @staticmethod
    def _record(record: DNSRecord, domain: str) -> str:
        if record.name.startswith("*."):
            # address= matches the name and every name below it
            return f"address=/{record_fqdn(record.name[2:], domain)}/{record.a}"
        fqdn = record_fqdn(record.name, domain)
        if record.a:
            return f"host-record={fqdn},{record.a}"
        return f"cname={fqdn},{record_fqdn(record.cname, domain)}"

    @staticmethod
    def _wg(spec: GroupSpec):
        """The WireGuard block when wg0 must run (enabled, tunnel subnet assigned)"""
        wg = spec.router.wireguard
        return wg if wg is not None and wg.enabled and wg.subnet else None

    def nft_conf(self, spec: GroupSpec) -> str:
        wg = self._wg(spec)
        # LAN -> WireGuard devices / BGP-announced addresses is routed, not masqueraded (replies to
        # them are conntrack'ed anyway)
        nets = [spec.cidr] + ([wg.subnet] if wg else []) + [r.prefix for r in self._bgp_ranges(spec)]
        local = f"{{ {', '.join(nets)} }}" if len(nets) > 1 else spec.cidr
        nat = (f"        ip saddr {spec.cidr} ip daddr != {local} masquerade\n" if spec.uplink else "")
        egress = ""
        if spec.router.egress.mode == "blocked":
            # Disconnected lab: what the group network sends through the router towards anything but the
            # lab itself (+ allow) is refused, every packet (not only new connections: switching to blocked
            # cuts running downloads too). Traffic to the router's own addresses (DNS, NTP, haproxy, the
            # registry, its uplink address) is not forwarded: it never reaches this chain.
            # `ct status dnat`: connections to a port the router publishes for a container (the registry's Quay pod,
            # podman DNAT) are forwarded to the container's address: they stay allowed.
            reachable = nets + spec.router.egress.allow
            # exempt sources (a jump host; disconnected cluster nodes installing their packages)
            exempt = sorted({e.source for e in spec.router.egress.exempt})
            egress = ("        ct status dnat accept\n"
                      + (f"        ip saddr {{ {', '.join(exempt)} }} accept\n" if exempt else "")
                      + f"        ip saddr {spec.cidr} ip daddr {{ {', '.join(reachable)} }} accept\n"
                      f"        ip saddr {spec.cidr} counter reject with icmp type admin-prohibited"
                      " comment \"vmm egress blocked\"\n")
        return (
            "#!/usr/sbin/nft -f\n"
            f"# Generated by VM Manager for group '{spec.name}': local changes are overwritten.\n"
            "table ip vmm_group\n"
            "delete table ip vmm_group\n"
            "table ip vmm_group {\n"
            "    chain forward {\n"
            "        type filter hook forward priority filter; policy accept;\n"
            f"{egress}"
            "    }\n"
            "    chain postrouting {\n"
            "        type nat hook postrouting priority srcnat; policy accept;\n"
            f"{nat}"
            "    }\n"
            "}\n"
        )

    def haproxy_conf(self, spec: GroupSpec) -> str:
        lines = [
            f"# Generated by VM Manager for group '{spec.name}': local changes are overwritten.",
            "global",
            "    log /dev/log local0",
            "    maxconn 4000",
            "",
            "defaults",
            "    mode tcp",
            "    log global",
            "    option tcplog",
            "    option dontlognull",
            "    retries 3",
            "    option redispatch",  # a backend that just died: retry the connection on another one
            "    timeout connect 5s",
            # long-lived watches (kubectl get -w, controllers) go through the load balancer
            "    timeout client 1h",
            "    timeout server 1h",
            "    timeout check 3s",
            "    default-server inter 3s fall 2 rise 2",
        ]
        for lb in spec.load_balancers:
            lines += ["", f"# {lb.owner or lb.name}", f"listen {lb.name}", f"    bind *:{lb.port}",
                      f"    mode {lb.mode}", "    balance roundrobin"]
            lines += [f"    server {lb.name}-{i} {backend} check" for i, backend in enumerate(lb.backends)]
        return "\n".join(lines) + "\n"

    def wg_conf(self, spec: GroupSpec) -> str:
        """wg-quick config without the private key: the router generates it once (WG_KEY) and PostUp
        loads it, so re-rendering never changes the router's identity"""
        wg = spec.router.wireguard
        net = ipaddress.IPv4Network(wg.subnet) if wg and wg.subnet else None
        lines = [f"# Generated by VM Manager for group '{spec.name}': local changes are overwritten.",
                 "[Interface]"]
        if net is not None:
            lines += [f"Address = {wg.router_ip()}/{net.prefixlen}", f"ListenPort = {wg.listen_port}",
                      f"PostUp = wg set %i private-key {WG_KEY}"]
        for peer in (wg.peers if wg else []):
            lines += ["", "[Peer]", f"# {peer.name}", f"PublicKey = {peer.public_key}",
                      f"AllowedIPs = {', '.join([f'{peer.ip}/32'] + peer.allowed_ips)}"]
            if peer.endpoint:
                lines += [f"Endpoint = {peer.endpoint}", "PersistentKeepalive = 25"]
        return "\n".join(lines) + "\n"

    def _wg_apply(self, spec: GroupSpec) -> str:
        if not self._wg(spec):
            return "{ systemctl disable --now wg-quick@wg0 >/dev/null 2>&1; true; }"
        # Routers created before WireGuard was supported: install wireguard-tools once. The key pair is
        # made once and kept; peers change live (syncconf), no tunnel restart
        return ("{ rpm -q wireguard-tools >/dev/null || dnf -y -q install wireguard-tools; }"
                " && mkdir -p /etc/wireguard && chmod 700 /etc/wireguard"
                f" && {{ test -s {WG_KEY} || (umask 077 && wg genkey > {WG_KEY}.tmp && mv {WG_KEY}.tmp {WG_KEY}); }}"
                f" && wg pubkey < {WG_KEY} > /etc/wireguard/public.key && chmod 600 {WG_CONF}"
                " && { restorecon -R /etc/wireguard 2>/dev/null; true; }"
                " && if systemctl is-active -q wg-quick@wg0; then"
                " wg-quick strip wg0 > /run/vmm-wg0.conf && wg syncconf wg0 /run/vmm-wg0.conf"
                f" && wg set wg0 private-key {WG_KEY}; rc=$?; rm -f /run/vmm-wg0.conf; test $rc = 0;"
                " else systemctl enable -q wg-quick@wg0 && systemctl restart wg-quick@wg0; fi"
                " && systemctl is-active wg-quick@wg0")

    @staticmethod
    def _bgp(spec: GroupSpec):
        """The BGP block when bgpd must run"""
        bgp = spec.router.bgp
        return bgp if bgp is not None and bgp.enabled else None

    def _bgp_ranges(self, spec: GroupSpec):
        bgp = self._bgp(spec)
        return bgp.announce_ranges if bgp else []

    def frr_conf(self, spec: GroupSpec) -> str:
        """FRR config: bgpd with dynamic neighbors on the group network (peer group LAB), explicit
        neighbors, routes accepted only inside the announce ranges, ECMP, nothing announced back"""
        bgp = spec.router.bgp
        lines = [f"! Generated by VM Manager for group '{spec.name}': local changes are overwritten.",
                 "frr defaults traditional", "hostname router", "log syslog informational", "!"]
        if bgp is None or not bgp.enabled:
            return "\n".join(lines) + "\n"
        # Only these prefixes (and more specific ones, e.g. a service /32) are accepted from peers
        if bgp.announce_ranges:
            lines += [f"ip prefix-list VMM-ANNOUNCE seq {5 * (i + 1)} permit {r.prefix} le 32"
                      for i, r in enumerate(bgp.announce_ranges)]
        else:
            lines.append("ip prefix-list VMM-ANNOUNCE seq 5 deny any")
        lines += ["!", "route-map VMM-IN permit 10", " match ip address prefix-list VMM-ANNOUNCE", "exit", "!",
                  "route-map VMM-OUT deny 10", "exit", "!"]
        remote = str(bgp.peer_asn) if bgp.peer_asn else "external"
        lines += [f"router bgp {bgp.asn}",
                  f" bgp router-id {spec.router.ip}",
                  " no bgp ebgp-requires-policy",
                  " no bgp default ipv4-unicast",
                  " no bgp network import-check",
                  # several peers announcing one prefix: use them all, even with different ASNs
                  " bgp bestpath as-path multipath-relax",
                  " timers bgp 10 30"]
        peers = []
        if bgp.listen:
            lines += [" neighbor LAB peer-group", f" neighbor LAB remote-as {remote}",
                      f" bgp listen range {spec.cidr} peer-group LAB", " bgp listen limit 200"]
            peers.append("LAB")
        for n in bgp.neighbors:
            lines.append(f" neighbor {n.ip} remote-as {n.asn}")
            if n.name or n.owner:
                lines.append(f" neighbor {n.ip} description {n.name or n.owner}")
            peers.append(n.ip)
        lines += [" !", " address-family ipv4 unicast", f"  maximum-paths {bgp.maximum_paths}",
                  f"  maximum-paths ibgp {bgp.maximum_paths}"]
        for p in peers:
            lines += [f"  neighbor {p} activate", f"  neighbor {p} route-map VMM-IN in",
                      f"  neighbor {p} route-map VMM-OUT out"]
        lines += [" exit-address-family", "exit", "!"]
        return "\n".join(lines) + "\n"

    def _bgp_apply(self, spec: GroupSpec) -> str:
        if not self._bgp(spec):
            return "{ systemctl disable --now frr >/dev/null 2>&1; true; }"
        # Routers created before BGP was supported: install frr once. bgpd on in /etc/frr/daemons; a config
        # change is applied by frr-reload (systemctl reload: sessions stay up), a first start restarts frr
        return ("{ rpm -q frr >/dev/null || dnf -y -q install frr; }"
                # ECMP over ports too (routers created before BGP have only ip_forward in their sysctl file)
                " && { grep -q fib_multipath_hash_policy /etc/sysctl.d/90-vmm-router.conf"
                " || echo 'net.ipv4.fib_multipath_hash_policy = 1' >> /etc/sysctl.d/90-vmm-router.conf; }"
                " && sysctl -qw net.ipv4.fib_multipath_hash_policy=1"
                " && if grep -q '^bgpd=yes' /etc/frr/daemons; then fresh=0;"
                " else sed -i 's/^bgpd=.*/bgpd=yes/' /etc/frr/daemons && fresh=1; fi"
                f" && chown frr:frr {FRR_CONF} && chmod 640 {FRR_CONF}"
                " && { restorecon -R /etc/frr 2>/dev/null; true; }"
                " && systemctl enable -q frr"
                " && if [ $fresh = 0 ] && systemctl is-active -q frr; then"
                " systemctl reload frr || systemctl restart frr; else systemctl restart frr; fi"
                " && systemctl is-active frr")

    @staticmethod
    def ntp_command(spec: GroupSpec) -> str:
        """The router (synced to the public pools through its uplink) serves NTP to the lab: OpenShift's
        installer checks the nodes' clock against it, and labs keep time without internet NTP."""
        allow = f"allow {spec.cidr}"
        return (f"{{ grep -qx '{allow}' /etc/chrony.conf || {{ echo '{allow}' >> /etc/chrony.conf"
                " && systemctl restart chronyd; }; true; }")

    def apply_command(self, spec: GroupSpec) -> str:
        base = (f"{self.ntp_command(spec)}; restorecon -R /etc/dnsmasq.d /etc/nftables 2>/dev/null; "
                f"nft -f {NFT_CONF} && systemctl stop dnsmasq && {{ sh {PRUNE_LEASES} || true; }}; "
                "systemctl start dnsmasq && systemctl is-active dnsmasq")
        base += " && " + self._wg_apply(spec)
        if spec.router.bgp is not None:
            base += " && " + self._bgp_apply(spec)
        if registry_router.apply_command(spec):
            base += " && " + registry_router.apply_command(spec)
        if not spec.load_balancers:
            return base + " && { systemctl disable --now haproxy >/dev/null 2>&1; true; }"
        # Routers created before load balancers existed have no haproxy yet: install it once.
        # haproxy_connect_any lets haproxy bind / connect to any port (-P: persistent, set only once
        # since it rebuilds the policy)
        return (base + " && { rpm -q haproxy >/dev/null || dnf -y -q install haproxy; }"
                " && { getsebool haproxy_connect_any 2>/dev/null | grep -q 'on$'"
                " || setsebool -P haproxy_connect_any 1 || true; }"
                f" && {{ restorecon {HAPROXY_CONF} 2>/dev/null; haproxy -c -q -f {HAPROXY_CONF}; }}"
                " && systemctl enable -q haproxy && systemctl reload-or-restart haproxy"
                " && systemctl is-active haproxy")

    def files(self, spec: GroupSpec) -> Dict[str, str]:
        """Spec-dependent files, re-rendered and pushed on every change"""
        files = {DNSMASQ_CONF: self.dnsmasq_conf(spec), NFT_CONF: self.nft_conf(spec),
                 HAPROXY_CONF: self.haproxy_conf(spec), PRUNE_LEASES: _PRUNE_LEASES_SH}
        if spec.router.wireguard is not None:
            files[WG_CONF] = self.wg_conf(spec)
        if spec.router.bgp is not None:
            files[FRR_CONF] = self.frr_conf(spec)
        files.update(registry_router.files(spec))
        return files

    def network_config(self, spec: GroupSpec) -> str:
        net = ipaddress.IPv4Network(spec.cidr)
        ethernets: Dict[str, Dict] = {}
        if spec.uplink:
            ethernets["uplink"] = {"match": {"macaddress": spec.router.uplink_mac}, "dhcp4": True}
        ethernets["lan"] = {
            "match": {"macaddress": spec.router.lan_mac},
            "dhcp4": False,
            "addresses": [f"{spec.router.ip}/{net.prefixlen}"],
        }
        return yaml.safe_dump({"version": 2, "ethernets": ethernets}, sort_keys=False)

    def render(self, spec: GroupSpec) -> RenderedRouter:
        self.validate(spec)
        ci = spec.cloud_init
        config = cloud_image_service.build_cloud_config(
            hostname="router", username=ci.username, password=ci.password,
            ssh_keys=[k.strip() for k in ci.ssh_keys if k.strip()], keyboard=ci.keyboard,
            fqdn=f"router.{spec.domain}")
        # haproxy is always installed (same dnf run, ~10 MB on disk) but only enabled when the spec
        # has load balancers: adding one later needs no dnf run on a live, memory-tight router
        # wireguard-tools too (tiny): enabling remote access later needs no dnf run either
        # frr too (BGP), enabled only when the spec has an enabled bgp block
        config["packages"] = ["qemu-guest-agent", "dnsmasq", "nftables", "policycoreutils-python-utils", "haproxy",
                              "wireguard-tools", "chrony", "frr"]
        # cc_mounts runs before package installation: the swap file absorbs dnf's metadata peak
        config["swap"] = {"filename": "/swapfile", "size": SWAP_SIZE, "maxsize": SWAP_SIZE}

        files = self.files(spec)
        static_files = {
            # EL's qemu-ga only allows a few commands (no guest-exec / guest-file-*): run it unrestricted
            "/etc/systemd/system/qemu-guest-agent.service.d/vmm-router.conf": (
                "[Service]\nExecStart=\n"
                "ExecStart=/usr/bin/qemu-ga --method=virtio-serial --path=/dev/virtio-ports/org.qemu.guest_agent.0\n"),
            "/etc/dnsmasq.conf": "user=dnsmasq\ngroup=dnsmasq\nconf-dir=/etc/dnsmasq.d,.rpmnew,.rpmsave,.rpmorig\n",
            "/etc/sysconfig/nftables.conf": f'include "{NFT_CONF}"\n',
            # ECMP (BGP routes with several next hops): hash on ports too, so connections spread over them
            "/etc/sysctl.d/90-vmm-router.conf": "net.ipv4.ip_forward = 1\nnet.ipv4.fib_multipath_hash_policy = 1\n",
        }
        config["write_files"] = [{"path": p, "content": c, "permissions": "0600" if p == WG_CONF else "0644"}
                                 for p, c in {**static_files, **files}.items()]
        config["runcmd"] = config.get("runcmd", []) + [
            "systemctl daemon-reload",
            "systemctl restart qemu-guest-agent",
            # SELinux stays enforcing; only the guest agent's domain is permissive, so config pushes work
            "semanage permissive -a virt_qemu_ga_t || setsebool -P virt_qemu_ga_run_unconfined on || true",
            "systemctl disable --now firewalld 2>/dev/null || true",
            "sysctl --system",
            "restorecon -R /etc/dnsmasq.conf /etc/dnsmasq.d /etc/nftables /etc/sysconfig/nftables.conf || true",
            "systemctl enable nftables && systemctl restart nftables",
            "systemctl enable dnsmasq && systemctl restart dnsmasq",
            self.ntp_command(spec),
            *([f"{self.apply_command(spec)} || true"] if spec.load_balancers or self._wg(spec) or self._bgp(spec) else []),
            f"mkdir -p {STATE_DIR}",
            f"if systemctl is-active -q dnsmasq; then touch {STATE_DIR}/ready; "
            f"else systemctl status dnsmasq > {STATE_DIR}/failed 2>&1; fi",
        ]
        user_data = "#cloud-config\n" + yaml.safe_dump(config, sort_keys=False)
        return RenderedRouter(user_data=user_data, network_config=self.network_config(spec), files=files,
                              apply_command=self.apply_command(spec))


class VyOSRouterBackend(RouterBackend):
    """Reserved: VyOS config commands via cloud-init vyos_config_commands (future-features §2.2)"""

    flavour = "vyos"

    def validate(self, spec: GroupSpec) -> None:
        raise ValueError("Router flavour 'vyos' is not supported yet: use 'el'")

    def render(self, spec: GroupSpec) -> RenderedRouter:
        self.validate(spec)
        raise NotImplementedError


BACKENDS: Dict[str, RouterBackend] = {b.flavour: b for b in (ELRouterBackend(), VyOSRouterBackend())}


def get_backend(flavour: str) -> RouterBackend:
    try:
        return BACKENDS[flavour]
    except KeyError:
        raise ValueError(f"Unknown router flavour '{flavour}' (known: {', '.join(BACKENDS)})")


# Router images, in order of preference, when the spec doesn't name one
EL_IMAGES: List[str] = ["almalinux-9", "almalinux-10", "rocky-9", "centos-9-stream", "centos-10-stream"]
